import { describe, it, expect } from 'vitest';
import {
  extractTextFromPdfBytes,
  parseCMapStream,
  decompressFlateStream,
  bootstrapProfileFromResume,
} from '../evidence/pdf-text-extractor.js';
import {
  generateResumePdfBlob,
  tailorCandidateResume,
} from '../tailoring/index.js';
import { createEmptyProfile } from '../candidate/profile.js';
import type { CandidateProfile, JobPosting } from '../index.js';
import { createJobPostingId } from '../types/ids.js';

describe('PDF Text Extractor & Profile Bootstrapper (Phase 18)', () => {
  it('parses CMap stream mappings accurately', () => {
    const cmapSample = `
/CIDInit /ProcSet findresource begin
12 dict begin
begincmap
1 begincodespacerange
<0000> <ffff>
endcodespacerange
2 beginbfchar
<0021> <0041>
<0022> <0042>
endbfchar
1 beginbfrange
<0030> <0032> <0061>
endbfrange
endcmap
`;
    const cmap = parseCMapStream(cmapSample);
    expect(cmap.get(0x0021)).toBe('A');
    expect(cmap.get(0x0022)).toBe('B');
    // bfrange: 0x30->'a', 0x31->'b', 0x32->'c'
    expect(cmap.get(0x0030)).toBe('a');
    expect(cmap.get(0x0031)).toBe('b');
    expect(cmap.get(0x0032)).toBe('c');
  });

  it('decompresses flate streams via Web DecompressionStream', async () => {
    const text = 'ApplyKit Local-First Copilot';
    const encoder = new TextEncoder();
    const data = encoder.encode(text);

    const cs = new CompressionStream('deflate');
    const writer = cs.writable.getWriter();
    const reader = cs.readable.getReader();

    const readPromise = (async () => {
      const chunks: Uint8Array[] = [];
      let total = 0;
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        if (value) {
          chunks.push(value);
          total += value.length;
        }
      }
      const out = new Uint8Array(total);
      let off = 0;
      for (const c of chunks) {
        out.set(c, off);
        off += c.length;
      }
      return out;
    })();

    await writer.write(data);
    await writer.close();
    const compressed = await readPromise;

    const decompressed = await decompressFlateStream(compressed);
    const decoded = new TextDecoder().decode(decompressed);
    expect(decoded).toBe(text);
  });

  it('extracts text from real vector PDF generated by @react-pdf/renderer', async () => {
    const base = createEmptyProfile();
    const profile: CandidateProfile = {
      ...base,
      identity: {
        ...base.identity,
        legalFirstName: 'Morgan',
        legalLastName: 'Reed',
        email: 'morgan.reed@example.com',
        phone: '+1 (555) 234-5678',
        location: { city: 'San Francisco', country: 'USA' },
      },
      experiences: [
        {
          id: 'exp_canon' as any,
          company: 'Distributed Systems Corp',
          title: 'Senior Distributed Systems Engineer',
          employmentType: 'full_time',
          location: 'Remote',
          isRemote: true,
          startDate: '2022-01',
          isCurrent: true,
          description: 'Led distributed messaging platform.',
          highlights: [
            'Architected real-time streaming pipeline processing 1M events/sec using Go and Kafka.',
            'Reduced 99th percentile query latency by 45% through custom caching in Redis.',
          ],
          technologiesUsed: ['Go', 'Kafka', 'Redis'],
          evidenceRefs: [],
        },
      ],
      skills: [
        { id: 'sk_go' as any, name: 'Go', normalizedName: 'go', category: 'language', proficiency: 'expert', evidenceRefs: [] },
        { id: 'sk_kafka' as any, name: 'Kafka', normalizedName: 'kafka', category: 'cloud_infrastructure', proficiency: 'advanced', evidenceRefs: [] },
      ],
      education: [
        {
          id: 'edu_cal' as any,
          institution: 'UC Berkeley',
          degree: 'B.S.',
          fieldOfStudy: 'Computer Science',
          endDate: '2021-05',
          isCompleted: true,
          honors: ['Cum Laude'],
          relevantCoursework: [],
          activities: [],
          evidenceRefs: [],
        },
      ],
    };

    const targetJob: JobPosting = {
      id: createJobPostingId('canonical_job'),
      url: 'https://canonical.com/careers/4581200',
      title: 'Distributed Systems Engineer',
      companyName: 'Canonical',
      location: 'Remote',
      workplaceType: 'remote',
      employmentType: 'full_time',
      requirements: [],
      metadata: {},
      parsedAt: '2026-09-28T12:00:00Z',
      rawDescription: 'Distributed systems role',
    };

    const tailored = tailorCandidateResume(targetJob, profile);
    const pdfBlob = await generateResumePdfBlob(tailored, profile);
    const pdfBuffer = await pdfBlob.arrayBuffer();
    const pdfBytes = new Uint8Array(pdfBuffer);

    expect(pdfBytes.length).toBeGreaterThan(1000);

    const extractedText = await extractTextFromPdfBytes(pdfBytes);
    expect(extractedText).toContain('Morgan Reed');
    expect(extractedText).toContain('morgan.reed@example.com');
    expect(extractedText).toContain('+1 (555) 234-5678');
    expect(extractedText).toContain('Senior Distributed Systems Engineer');
    expect(extractedText).toContain('Distributed Systems Corp');
    expect(extractedText).toContain('Architected real-time streaming pipeline processing 1M events/sec using Go and Kafka.');
    expect(extractedText).toContain('UC Berkeley');
    expect(extractedText).toContain('B.S. in Computer Science');
  });

  it('bootstraps full CandidateProfile and decomposes EvidenceGraph from PDF binary', async () => {
    const base = createEmptyProfile();
    const profile: CandidateProfile = {
      ...base,
      identity: {
        ...base.identity,
        legalFirstName: 'Alex',
        legalLastName: 'Morgan',
        email: 'alex.morgan@example.com',
        phone: '+1 (555) 345-6789',
      },
      experiences: [
        {
          id: 'exp_cloud' as any,
          company: 'CloudScale Technologies',
          title: 'Staff Distributed Systems Engineer',
          employmentType: 'full_time',
          location: 'Remote',
          isRemote: true,
          startDate: '2021-03',
          isCurrent: true,
          description: 'Distributed infrastructure lead.',
          highlights: [
            'Engineered multi-region Raft consensus clustering in Go handling 250k RPCs/sec.',
            'Reduced tail latency SLA breaches by 60% with zero data loss.',
          ],
          technologiesUsed: ['Go', 'Kubernetes'],
          evidenceRefs: [],
        },
      ],
    };

    const targetJob: JobPosting = {
      id: createJobPostingId('job_test'),
      url: 'https://example.com/jobs/1',
      title: 'Distributed Systems Engineer',
      companyName: 'CloudScale',
      location: 'Remote',
      workplaceType: 'remote',
      employmentType: 'full_time',
      requirements: [],
      metadata: {},
      parsedAt: '2026-09-28T12:00:00Z',
      rawDescription: 'Cloud role',
    };

    const tailored = tailorCandidateResume(targetJob, profile);
    const pdfBlob = await generateResumePdfBlob(tailored, profile);
    const pdfBuffer = await pdfBlob.arrayBuffer();

    const bootstrapped = await bootstrapProfileFromResume(pdfBuffer, 'alex_morgan_resume.pdf');

    expect(bootstrapped.profile).toBeDefined();
    expect(bootstrapped.profile.identity.legalFirstName).toBe('Alex');
    expect(bootstrapped.profile.identity.legalLastName).toBe('Morgan');
    expect(bootstrapped.profile.identity.email).toBe('alex.morgan@example.com');
    expect(bootstrapped.profile.identity.phone).toBe('+1 (555) 345-6789');

    expect(bootstrapped.profile.experiences.length).toBeGreaterThan(0);
    const exp = bootstrapped.profile.experiences[0];
    expect(exp?.title).toContain('Distributed Systems Engineer');
    expect(exp?.highlights.length).toBeGreaterThanOrEqual(1);

    // Verify EvidenceGraph decomposition
    expect(bootstrapped.evidence.length).toBeGreaterThan(0);
    const sampleEvidence = bootstrapped.evidence[0];
    expect(sampleEvidence?.source.type).toBe('resume_bullet');
    expect(sampleEvidence?.confidenceScore).toBeGreaterThanOrEqual(0.8);
  });

  it('bootstraps CandidateProfile from Markdown resume string', async () => {
    const mdResume = `
# Jordan Taylor
jordan.taylor@example.com | +1 (555) 456-7890 | Seattle, WA
https://linkedin.com/in/jordantaylor | https://github.com/jordantaylor

## Professional Summary
Senior Distributed Systems Architect with 8+ years designing fault-tolerant stream pipelines.

## Work Experience
### Principal Systems Engineer | Apex Distributed Systems
*Mar 2021 – Present*
- Architected active-active event broker in Rust processing 500k messages/sec.
- Mentored 6 distributed systems engineers on memory safety and concurrency.

## Education
B.S. in Computer Engineering | University of Washington | 2017

## Technical Skills
Rust, Go, Kafka, Kubernetes, Distributed Systems, Linux
`;

    const bootstrapped = await bootstrapProfileFromResume(mdResume, 'resume.md');

    expect(bootstrapped.profile.identity.legalFirstName).toBe('Jordan');
    expect(bootstrapped.profile.identity.legalLastName).toBe('Taylor');
    expect(bootstrapped.profile.identity.email).toBe('jordan.taylor@example.com');
    expect(bootstrapped.profile.identity.phone).toBe('+1 (555) 456-7890');
    expect(bootstrapped.profile.identity.location.city).toBe('Seattle');

    expect(bootstrapped.profile.experiences.length).toBe(1);
    expect(bootstrapped.profile.experiences[0]?.title).toBe('Principal Systems Engineer');
    expect(bootstrapped.profile.experiences[0]?.company).toBe('Apex Distributed Systems');
    expect(bootstrapped.profile.experiences[0]?.highlights.length).toBe(2);

    expect(bootstrapped.profile.education.length).toBe(1);
    expect(bootstrapped.profile.education[0]?.degree).toBe('B.S. in Computer Engineering');
    expect(bootstrapped.profile.education[0]?.institution).toBe('University of Washington');

    expect(bootstrapped.evidence.length).toBeGreaterThan(0);
  });

  it('bootstraps CandidateProfile directly from ApplyKit JSON export', async () => {
    const base = createEmptyProfile();
    const profile: CandidateProfile = {
      ...base,
      identity: {
        ...base.identity,
        legalFirstName: 'Taylor',
        legalLastName: 'Swift',
        email: 'taylor@example.com',
        phone: '+1 (555) 111-2222',
      },
      experiences: [
        {
          id: 'exp_1' as any,
          company: 'Swift Systems',
          title: 'Lead Architect',
          employmentType: 'full_time',
          location: 'Remote',
          isRemote: true,
          startDate: '2020-01',
          isCurrent: true,
          description: 'Architecture lead',
          highlights: ['Designed high availability distributed storage'],
          technologiesUsed: ['Rust'],
          evidenceRefs: [],
        },
      ],
    };

    const jsonString = JSON.stringify(profile);
    const bootstrapped = await bootstrapProfileFromResume(jsonString, 'backup.json');

    expect(bootstrapped.profile.identity.legalFirstName).toBe('Taylor');
    expect(bootstrapped.profile.identity.legalLastName).toBe('Swift');
    expect(bootstrapped.profile.experiences.length).toBe(1);
    expect(bootstrapped.profile.experiences[0]?.company).toBe('Swift Systems');
  });
});
