/**
 * @fileoverview Google Gemini generateContent API Provider.
 *
 * Implements native JSON mode via generationConfig.responseMimeType = "application/json".
 * Invariant: Invoked exclusively from Extension Service Worker.
 */

import type {
  AIRequest,
  AIResponse,
  AIProviderCapabilities,
  FinishReason,
  TokenUsage,
} from '@applykit/domain';
import { BaseHttpProvider } from './base-provider.js';

interface GeminiGenerateContentResponse {
  candidates?: Array<{
    content?: {
      parts?: Array<{
        text?: string;
      }>;
    };
    finishReason?: string;
  }>;
  usageMetadata?: {
    promptTokenCount?: number;
    candidatesTokenCount?: number;
    totalTokenCount?: number;
  };
}

export class GeminiProvider extends BaseHttpProvider {
  readonly id = 'gemini';
  readonly displayName = 'Google Gemini (Flash / Pro)';
  readonly capabilities: AIProviderCapabilities = {
    supportsStreaming: true,
    supportsJsonSchema: true,
    maxContextTokens: 1000000,
    isLocal: false,
  };

  constructor(
    apiKey: string,
    modelName = 'gemini-flash-lite-latest',
    timeoutMs = 30000,
    customFetch?: typeof fetch
  ) {
    super(apiKey, modelName, timeoutMs, customFetch);
  }

  async complete<T = unknown>(request: AIRequest): Promise<AIResponse<T>> {
    const candidateModels = Array.from(
      new Set([
        this.modelName,
        'gemini-flash-lite-latest',
        'gemini-3.5-flash-lite',
        'gemini-3.1-flash-lite',
        'gemini-3.8-flash',
        'gemini-3.7-flash',
        'gemini-3.5-flash',
        'gemini-2.0-flash',
      ])
    );

    const body: Record<string, unknown> = {
      contents: [
        {
          role: 'user',
          parts: [{ text: request.prompt }],
        },
      ],
      generationConfig: {
        responseMimeType: 'application/json',
        temperature: request.temperature ?? 0.1,
        maxOutputTokens: Math.max(request.maxTokens ?? 4096, 4096),
      },
    };

    if (request.systemPrompt) {
      body.systemInstruction = {
        parts: [{ text: request.systemPrompt }],
      };
    }

    let lastError: Error | null = null;
    let quotaError: Error | null = null;
    let data: GeminiGenerateContentResponse | null = null;

    for (const model of candidateModels) {
      const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${this.apiKey}`;
      try {
        const res = await this.fetchWithRetry(url, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'x-goog-api-key': this.apiKey,
          },
          body: JSON.stringify(body),
        });

        if (!res.ok) {
          const errorBody = await res.text();
          const err = new Error(`Google Gemini API request failed (${res.status}): ${errorBody}`);
          if (res.status === 429) {
            quotaError = err;
          }
          throw err;
        }

        data = (await res.json()) as GeminiGenerateContentResponse;
        if (data.candidates && data.candidates.length > 0) {
          break;
        }
      } catch (err) {
        lastError = err instanceof Error ? err : new Error(String(err));
        // Continue to fallback model on temporary capacity, quota (429), or model retirement (404)
        continue;
      }
    }

    if (!data || !data.candidates || data.candidates.length === 0) {
      throw quotaError || lastError || new Error('No completion generated by Google Gemini models.');
    }

    const candidate = data.candidates[0];
    const rawText = candidate?.content?.parts?.[0]?.text || '';

    const finishReason: FinishReason =
      candidate?.finishReason === 'STOP'
        ? 'stop'
        : candidate?.finishReason === 'MAX_TOKENS'
        ? 'length'
        : candidate?.finishReason === 'SAFETY'
        ? 'content_filter'
        : 'unknown';

    const usage: TokenUsage | undefined = data.usageMetadata
      ? {
          promptTokens: data.usageMetadata.promptTokenCount ?? 0,
          completionTokens: data.usageMetadata.candidatesTokenCount ?? 0,
          totalTokens: data.usageMetadata.totalTokenCount ?? 0,
        }
      : undefined;

    const parsed = this.parseJsonResult<T>(rawText);

    return {
      rawText,
      parsed,
      usage,
      finishReason,
    };
  }
}
